linters:
  enable:
    - errorlint
    - unconvert
    - unparam
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gofmt
    - gosec
    - nilerr
    - usestdlibvars
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errname
    - gocheckcompilerdirectives
    - gochecknoinits
    - mirror
    - misspell
    - predeclared
    - reassign
    - thelper
    - wastedassign
    - godox
    - lll
    - errchkjson
    - funlen
    - nestif
    - prealloc

linters-settings:
  funlen:
    lines: -1 # don't count lines, only statements
    statements: 50
    ignore-comments: true
  nestif:
    min-complexity: 4
